services:
  php:
    build:
      dockerfile: docker/php/Dockerfile
    environment:
      PHP_IDE_CONFIG: "serverName=xdebug-docker"
      XDEBUG_CONFIG: "client_host=host.docker.internal start_with_request=trigger log_level=0"
      XDEBUG_MODE: "debug"
      XDEBUG_SESSION: "PHPSTORM"
    extra_hosts:
      - "host.docker.internal:172.30.208.1"
    volumes:
      - ./:/var/www/html
    working_dir: /var/www/html
    ports:
      - "8000:8000"

  mysql:
    image: mysql:8.0
    volumes:
      - db-data:/var/lib/mysql/:rw
    environment:
      MYSQL_DATABASE: db_name
      MYSQL_USER: db_user
      MYSQL_PASSWORD: db_password
      MYSQL_ALLOW_EMPTY_PASSWORD: 'yes'
    command: --default-authentication-plugin=mysql_native_password
    ports:
      - "127.0.0.1:3306:3306"

volumes:
  db-data:
